# Disable check for missing top-level documentation of classes and modules.
Style/Documentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/MethodLength:
  Enabled: false
